/*********************************************************************************
  macDbg.h 
  Copyright (c)Meshnetics.

  Description:
    TBD.
          
  History:
    09/11/07 A. Mandychev - Created.
**********************************************************************************/
#ifndef _MACDBG_H
#define _MACDBG_H

/*********************************************************************************
 ASSERT is used for debugging wrong conditions

 Types of messages:
   

*********************************************************************************/
  /***************************************************************
    Defines with 1 in the high-order bit should not be used as enum is signed int type
  ***************************************************************/
  typedef enum
  {
  /***********************************
    MAC & PHY section. Range 0x1000 - 0x1FFFF
  ****** *****************************/
    // PHY asserts' ID.
    PHYRFIRQDISPATCHER_RFINTERRUPTSUBROUTINE_0        = 0x1001,
    PHYTXFRAME_DATAREQ_0                              = 0x1002,
    PHYPIB_PHYSETPIBPARAM_0                           = 0x1003,
    PHYPIB_PHYGETPIBPARAM_0                           = 0x1004,
    PHYTXFRAME_PHYDATAREQ_0                           = 0x1005,
    PHYRXFRAME_PHYDOWNLOADFRAME_0                     = 0x1006,
    MACPHYMACENV_GETSYMBOLPEROCTET_0                  = 0x1007,
    MACPHYMACENV_GETPHYSYMBOLDURATION_0               = 0x1008,
    PHYSET_PHYSETREQ_0                                = 0x1009,
    PHYSETTRXSTATE_PHYSETTRXSTATEREQ_0                = 0x100A,
		PHYRFSPIPROTO_PHYENCRYPTBYSPI_0										= 0x100B,
		MACPHYPIBSERVER_STORETXPOWER_0                    = 0x100C,
		PHYSET_CONVERTTXPOWER_0                           = 0x100D,
		PHYSET_PHYSETREQ_1                                = 0x100E,
		MACPHYMACENV_SETPIBATTR_0                         = 0x100F,
		MACPHYMACENV_GETPIBATTR_0                         = 0x1010,
		
    // MAC_HWD asserts' ID.
    MACHWDFRAMEROUTINE_MACHWDCOMPOSEFRAME_0           = 0x1021,
    MACHWDPIB_MACHWDGETPIBPARAM_0                     = 0x1022,
    MACHWDGETHANDLER_MACHWDGETREQHANDLER_0            = 0x1023,
    MACHWDRXFRAMEHANDLER_GETCURRENTCHANNEL_0          = 0x1024,
    MACHWDMANAGER_TASKHANDLER_0                       = 0x1025,
    MACHWDMANAGER_TASKHANDLER_1                       = 0x1026,
    MACHWDMANAGER_TASKHANDLER_2                       = 0x1027,
    MACHWDMANAGER_SENDREQTOHANDLER_0                  = 0x1028,
    MACHWDMANAGER_DISPATCHETASKTOHANDLER_0            = 0x1029,
    MACHWDEDHNDLR_MACHWDEDHANDLER_0                   = 0x102A,
    MACHWDEDHNDLR_MACHWDEDHANDLER_1                   = 0x102B,
    MACHWDEDHNDLR_MACHWDEDTASKHANDLER_0               = 0x102C,
    MACHWDTRXHANDLER_MACHWDTRXREQHANDLER_0            = 0x102D,
    MACHWDTRXHANDLER_TRXTASKHANDLER_0                 = 0x102E,
    MACHWDSETHANDLER_MACHWDSETREQHANDLER_0            = 0x102F,
    MACHWDSETHANDLER_MACHWDSETREQHANDLER_1            = 0x1030,
    MACHWDSETHANDLER_MACHWDSETTASKHANDLER_0           = 0x1031,
    MACHWDSETHANDLER_MACHWDSETTASKHANDLER_1           = 0x1032,
    MACHWDSETHANDLER_EXECUTESETREQ_0                  = 0x1033,
    MACHWDSETHANDLER_EXECUTEPHYSETREQ_0               = 0x1034,
    MACHWDSETHANDLER_SETRXONSTATE_0                   = 0x1035,
    MACHWDTXFRAMEHANDLER_MACHWDTXFRAMEREQHANDLER_0    = 0x1036,
    MACHWDTXFRAMEHANDLER_MACHWDTXFRAMETASKHANDLER_0   = 0x1037,
    MACHWDTXFRAMEHANDLER_EXECUTEPHYDATAREQ_0          = 0x1038,
    MACHWDTXFRAMEHANDLER_SETRXONSTATE_0               = 0x1039,
    MACHWDRESETHANDLER_MACHWDRESETREQHANDLER_0        = 0x1040,
    MACHWDTXFRAMEHANDLER_EXECUTEDATAREQ_0             = 0x1041,
    MACHWDTXFRAMEHANDLER_MACHWDTXFRAMETASKHANDLER_1   = 0x1042,
    MACHWDGETHANDLER_MACHWDGETREQHANDLER_1            = 0x1043,
    MACHWDSETHANDLER_MACHWDSETREQHANDLER_2            = 0x1044,
    MACHWDTRXCTRL_GETPHYTRXCMD_0                      = 0x1045,
    MACHWDTRXCTRL_CONVERTTRXCMDTOTRXSTATE_0           = 0x1046,
    MACHWDEDHANDLER_MACHWDEDREQHANDLER_2              = 0x1047,
    MACHWDTXFRAMEHANDLER_GETDATASTATUS_0              = 0x1048,
    MACHWDENCRYPTHANDLER_MACHWDENCRYPTREQHANDLER_0    = 0x1049,
    MACHWDENCRYPTHANDLER_MACHWDENCRYPTREQHANDLER_1    = 0x104A,
    MACHWDENCRYPTHANDLER_MACHWDENCRYPTTASKHANDLER_0   = 0x104B,
    MACHWDRNDHANDLER_MACHWDRNDREQHANDLER_0            = 0x104C,
    MACHWDRNDHANDLER_MACHWDRNDREQHANDLER_1            = 0x104D,
    MACHWDRNDHANDLER_MACHWDRNDTASKHANDLER_0           = 0x104E,
    MACHWDBATMONHANDLER_MACHWDBATMONREQHANDLER_0      = 0x104F,
    MACHWDBATMONHANDLER_MACHWDBATMONREQHANDLER_1      = 0x1050,
    MACHWDBATMONHANDLER_MACHWDBATMONTASKHANDLER_0     = 0x1051,
    MACHWDBATMONHANDLER_MACHWDBATMONTASKHANDLER_1     = 0x1052,

    // MAC_HWI asserts' ID.
    MACHWIDATAHANDLER_CONVERTMACHWDDATACONFIRMTYPES_0 = 0x1080,
    MACHWIHWDREQMEMPOLL_GETREQMEM_0                   = 0x1081,
    MACHWIHWDREQMEMPOLL_RELEASEREQMEM_0               = 0x1082,
    MACHWIMANAGER_SENDREQTOHANDLER_0                  = 0x1083,
    MACHWIMANAGER_TASKHANDLER_0                       = 0x1084,
    MACHWIMANAGER_TASKHANDLER_1                       = 0x1085,
    MACHWISCANHANDLER_MACHWDSETCONFIRM_0              = 0x1086,
    MACHWISCANHANDLER_MACHWDSETCONFIRM_1              = 0x1087,
    MACHWISCANHANDLER_MACHWIBEACONINDICATION_0        = 0x1088,
    MACHWIASSOCIATEHANDLER_MACHWDSETCONFIRM_0         = 0x1089,
    MACHWIASSOCIATEHANDLER_MACHWDSETTRXSTATECONFIRM_0 = 0x108A,
    MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_0        = 0x108B,
    MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_1        = 0x108C,
    MACHWIASSOCIATEHANDLER_MACHWDDATACONFIRM_2        = 0x108D,
    MACHWIASSOCIATEHANDLER_ASSOCIATETIMERFIRED_0      = 0x108E,
    MACHWITRANSACTIONQUEUE_GETDSTADDRINFO_0           = 0x108F,
    MACHWITRANSACTIONQUEUE_GETDSTADDRINFO_1           = 0x1090,
    MACHWITRANSACTIONHANDLER_MACHWDDATACONFIRM_0      = 0x1091,
    MACHWITRANSACTIONHANDLER_MACHWDDATACONFIRM_1      = 0x1092,
    MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_0   = 0x1093,
    MACHWITRANSACTIONHANDLER_SENDTRANSACTIONEVENT_1   = 0x1094,
    MACHWITRANSACTIONQUEUE_GETACTIVATEDTRANSACTION_0  = 0x1095,
    MACHWISTARTHANDLER_MACHWDSETCONFIRM_0             = 0x1096,
    MACHWISTARTHANDLER_MACHWDSETCONFIRM_1             = 0x1097,
    MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_0      = 0x1098,
    MACHWIPOLLHANDLER_MACHWDDATACONFIRM_0             = 0x1099,
    MACHWIPOLLHANDLER_ISITREQUESTEDDATA_0             = 0x109A,
    MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_1      = 0x109B,
    MACHWISCANHANDLER_MACHWDSETTRXSTATECONFIRM_2      = 0x109C,
    MACHWISCANHANDLER_MACHWISCANREQHANDLER_0          = 0x109D,
    MACHWISCANHANDLER_MACHWDSETCONFIRM_2              = 0x109E,
    MACHWISCANHANDLER_MACHWDSETCONFIRM_3              = 0x109F,
    MACHWISCANHANDLER_MACHWDSETCONFIRM_4              = 0x10A0,
    MACHWIDISASSOCIATEHANDLER_MACHWDDATACONFIRM_0     = 0x10A1,
    MACHWISWITCHRXCTRL_SWITCHRXONWHENIDLE_0           = 0x10A2,
    MACHWIMANAGER_MACHWISENDCONFTOUPPERLAYER_0        = 0x10A3,
    MACHWISETHANDLER_MACHWDSETCONFIRM_0               = 0x10A4,
    MACHWIGETHANDLER_MACHWDGETCONFIRM_0               = 0x10A5,
    MACHWISTARTHANDLER_MACHWISTARTREQHANDLER_0        = 0x10A6,  
    MACHWIRESETHANDLER_MACHWDSETCONFIRM_0             = 0x10A7,
    MACHWIDISASSOCIATEHANDLER_MACHWDSETCONFIRM_0      = 0x10A8,
    MACHWISTARTHANDLER_MACHWDDATACONFIRM_0            = 0x10A9,
    MACHWIENCRYPTHANDLER_MACHWISETKEYREQ_0            = 0x10AA,
    MACHWIENCRYPTHANDLER_MACHWDENCRYPTCONF_0          = 0x10AB,
    MACHWIENCRYPTHANDLER_MACHWIENCRYPTREQHANDLER_0    = 0x10AC,
  } MacDbgCode_t;

#endif /* _MACDBG_H */

//end of macDbg.h

